
// This file has been generated by the GUI designer. Do not modify.
namespace Pinta
{
	public partial class ResizeCanvasDialog
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.RadioButton percentageRadio;
		
		private global::Gtk.SpinButton percentageSpinner;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.RadioButton absoluteRadio;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.SpinButton widthSpinner;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.SpinButton heightSpinner;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.CheckButton aspectCheckbox;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Alignment alignment1;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Button CenterButton;
		
		private global::Gtk.Button EButton;
		
		private global::Gtk.Button NButton;
		
		private global::Gtk.Button NEButton;
		
		private global::Gtk.Button NWButton;
		
		private global::Gtk.Button SButton;
		
		private global::Gtk.Button SEButton;
		
		private global::Gtk.Button SWButton;
		
		private global::Gtk.Button WButton;
		
		private global::Gtk.Alignment alignment2;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Pinta.ResizeCanvasDialog
			this.Name = "Pinta.ResizeCanvasDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Resize Canvas");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.DefaultWidth = 300;
			this.DefaultHeight = 200;
			// Internal child Pinta.ResizeCanvasDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(12));
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.percentageRadio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("By percentage:"));
			this.percentageRadio.CanFocus = true;
			this.percentageRadio.Name = "percentageRadio";
			this.percentageRadio.DrawIndicator = true;
			this.percentageRadio.UseUnderline = true;
			this.percentageRadio.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hbox1.Add (this.percentageRadio);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.percentageRadio]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.percentageSpinner = new global::Gtk.SpinButton (1D, 1000D, 1D);
			this.percentageSpinner.CanFocus = true;
			this.percentageSpinner.Name = "percentageSpinner";
			this.percentageSpinner.Adjustment.PageIncrement = 10D;
			this.percentageSpinner.ClimbRate = 1D;
			this.percentageSpinner.Numeric = true;
			this.percentageSpinner.Value = 100D;
			this.hbox1.Add (this.percentageSpinner);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.percentageSpinner]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = "%";
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.absoluteRadio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("By absolute size:"));
			this.absoluteRadio.CanFocus = true;
			this.absoluteRadio.Name = "absoluteRadio";
			this.absoluteRadio.DrawIndicator = true;
			this.absoluteRadio.UseUnderline = true;
			this.absoluteRadio.Group = this.percentageRadio.Group;
			this.hbox2.Add (this.absoluteRadio);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.absoluteRadio]));
			w6.Position = 0;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Width:");
			this.hbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.widthSpinner = new global::Gtk.SpinButton (1D, 10000D, 1D);
			this.widthSpinner.Sensitive = false;
			this.widthSpinner.CanFocus = true;
			this.widthSpinner.Name = "widthSpinner";
			this.widthSpinner.Adjustment.PageIncrement = 10D;
			this.widthSpinner.ClimbRate = 1D;
			this.widthSpinner.Numeric = true;
			this.hbox3.Add (this.widthSpinner);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.widthSpinner]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("pixels");
			this.hbox3.Add (this.label4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label4]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Height:");
			this.hbox4.Add (this.label3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label3]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.heightSpinner = new global::Gtk.SpinButton (1D, 10000D, 1D);
			this.heightSpinner.Sensitive = false;
			this.heightSpinner.CanFocus = true;
			this.heightSpinner.Name = "heightSpinner";
			this.heightSpinner.Adjustment.PageIncrement = 10D;
			this.heightSpinner.ClimbRate = 1D;
			this.heightSpinner.Numeric = true;
			this.hbox4.Add (this.heightSpinner);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.heightSpinner]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("pixels");
			this.hbox4.Add (this.label5);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label5]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox2.Add (this.hbox4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
			w15.Position = 3;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.aspectCheckbox = new global::Gtk.CheckButton ();
			this.aspectCheckbox.Sensitive = false;
			this.aspectCheckbox.CanFocus = true;
			this.aspectCheckbox.Name = "aspectCheckbox";
			this.aspectCheckbox.Label = global::Mono.Unix.Catalog.GetString ("Maintain aspect ratio");
			this.aspectCheckbox.Active = true;
			this.aspectCheckbox.DrawIndicator = true;
			this.aspectCheckbox.UseUnderline = true;
			this.vbox2.Add (this.aspectCheckbox);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.aspectCheckbox]));
			w16.Position = 4;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.hbox5.Add (this.alignment1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.alignment1]));
			w17.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.CenterButton = new global::Gtk.Button ();
			this.CenterButton.WidthRequest = 30;
			this.CenterButton.HeightRequest = 30;
			this.CenterButton.CanFocus = true;
			this.CenterButton.Name = "CenterButton";
			this.CenterButton.UseUnderline = true;
			global::Gtk.Image w18 = new global::Gtk.Image ();
			this.CenterButton.Image = w18;
			this.table1.Add (this.CenterButton);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.CenterButton]));
			w19.TopAttach = ((uint)(1));
			w19.BottomAttach = ((uint)(2));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.EButton = new global::Gtk.Button ();
			this.EButton.WidthRequest = 30;
			this.EButton.HeightRequest = 30;
			this.EButton.CanFocus = true;
			this.EButton.Name = "EButton";
			this.EButton.UseUnderline = true;
			global::Gtk.Image w20 = new global::Gtk.Image ();
			this.EButton.Image = w20;
			this.table1.Add (this.EButton);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1 [this.EButton]));
			w21.TopAttach = ((uint)(1));
			w21.BottomAttach = ((uint)(2));
			w21.LeftAttach = ((uint)(2));
			w21.RightAttach = ((uint)(3));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.NButton = new global::Gtk.Button ();
			this.NButton.WidthRequest = 30;
			this.NButton.HeightRequest = 30;
			this.NButton.CanFocus = true;
			this.NButton.Name = "NButton";
			this.NButton.UseUnderline = true;
			global::Gtk.Image w22 = new global::Gtk.Image ();
			this.NButton.Image = w22;
			this.table1.Add (this.NButton);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1 [this.NButton]));
			w23.LeftAttach = ((uint)(1));
			w23.RightAttach = ((uint)(2));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.NEButton = new global::Gtk.Button ();
			this.NEButton.WidthRequest = 30;
			this.NEButton.HeightRequest = 30;
			this.NEButton.CanFocus = true;
			this.NEButton.Name = "NEButton";
			this.NEButton.UseUnderline = true;
			global::Gtk.Image w24 = new global::Gtk.Image ();
			this.NEButton.Image = w24;
			this.table1.Add (this.NEButton);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1 [this.NEButton]));
			w25.LeftAttach = ((uint)(2));
			w25.RightAttach = ((uint)(3));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.NWButton = new global::Gtk.Button ();
			this.NWButton.WidthRequest = 30;
			this.NWButton.HeightRequest = 30;
			this.NWButton.CanFocus = true;
			this.NWButton.Name = "NWButton";
			this.NWButton.UseUnderline = true;
			global::Gtk.Image w26 = new global::Gtk.Image ();
			this.NWButton.Image = w26;
			this.table1.Add (this.NWButton);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1 [this.NWButton]));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.SButton = new global::Gtk.Button ();
			this.SButton.WidthRequest = 30;
			this.SButton.HeightRequest = 30;
			this.SButton.CanFocus = true;
			this.SButton.Name = "SButton";
			this.SButton.UseUnderline = true;
			global::Gtk.Image w28 = new global::Gtk.Image ();
			this.SButton.Image = w28;
			this.table1.Add (this.SButton);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table1 [this.SButton]));
			w29.TopAttach = ((uint)(2));
			w29.BottomAttach = ((uint)(3));
			w29.LeftAttach = ((uint)(1));
			w29.RightAttach = ((uint)(2));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.SEButton = new global::Gtk.Button ();
			this.SEButton.WidthRequest = 30;
			this.SEButton.HeightRequest = 30;
			this.SEButton.CanFocus = true;
			this.SEButton.Name = "SEButton";
			this.SEButton.UseUnderline = true;
			global::Gtk.Image w30 = new global::Gtk.Image ();
			this.SEButton.Image = w30;
			this.table1.Add (this.SEButton);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table1 [this.SEButton]));
			w31.TopAttach = ((uint)(2));
			w31.BottomAttach = ((uint)(3));
			w31.LeftAttach = ((uint)(2));
			w31.RightAttach = ((uint)(3));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.SWButton = new global::Gtk.Button ();
			this.SWButton.WidthRequest = 30;
			this.SWButton.HeightRequest = 30;
			this.SWButton.CanFocus = true;
			this.SWButton.Name = "SWButton";
			this.SWButton.UseUnderline = true;
			global::Gtk.Image w32 = new global::Gtk.Image ();
			this.SWButton.Image = w32;
			this.table1.Add (this.SWButton);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table1 [this.SWButton]));
			w33.TopAttach = ((uint)(2));
			w33.BottomAttach = ((uint)(3));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.WButton = new global::Gtk.Button ();
			this.WButton.WidthRequest = 30;
			this.WButton.HeightRequest = 30;
			this.WButton.CanFocus = true;
			this.WButton.Name = "WButton";
			this.WButton.UseUnderline = true;
			global::Gtk.Image w34 = new global::Gtk.Image ();
			this.WButton.Image = w34;
			this.table1.Add (this.WButton);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table1 [this.WButton]));
			w35.TopAttach = ((uint)(1));
			w35.BottomAttach = ((uint)(2));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox5.Add (this.table1);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.table1]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.hbox5.Add (this.alignment2);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.alignment2]));
			w37.Position = 2;
			this.vbox2.Add (this.hbox5);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
			w38.PackType = ((global::Gtk.PackType)(1));
			w38.Position = 5;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Anchor:");
			this.vbox2.Add (this.label6);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label6]));
			w39.PackType = ((global::Gtk.PackType)(1));
			w39.Position = 6;
			w39.Expand = false;
			w39.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox2.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator1]));
			w40.PackType = ((global::Gtk.PackType)(1));
			w40.Position = 7;
			w40.Expand = false;
			w40.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w41.Position = 0;
			w41.Expand = false;
			w41.Fill = false;
			// Internal child Pinta.ResizeCanvasDialog.ActionArea
			global::Gtk.HButtonBox w42 = this.ActionArea;
			w42.Name = "dialog1_ActionArea";
			w42.Spacing = 10;
			w42.BorderWidth = ((uint)(5));
			w42.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w43 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w42 [this.buttonCancel]));
			w43.Expand = false;
			w43.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w44 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w42 [this.buttonOk]));
			w44.Position = 1;
			w44.Expand = false;
			w44.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
