
// This file has been generated by the GUI designer. Do not modify.
namespace Pinta.Gui.Widgets
{
	public partial class HScaleSpinButtonWidget
	{
		private global::Gtk.VBox vbox;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label label;
		
		private global::Gtk.HSeparator hseparator;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.HScale hscale;
		
		private global::Gtk.SpinButton spin;
		
		private global::Gtk.Button button;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Pinta.Gui.Widgets.HScaleSpinButtonWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Pinta.Gui.Widgets.HScaleSpinButtonWidget";
			// Container child Pinta.Gui.Widgets.HScaleSpinButtonWidget.Gtk.Container+ContainerChild
			this.vbox = new global::Gtk.VBox ();
			this.vbox.Name = "vbox";
			this.vbox.Spacing = 6;
			// Container child vbox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label = new global::Gtk.Label ();
			this.label.Name = "label";
			this.label.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hbox1.Add (this.label);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hseparator = new global::Gtk.HSeparator ();
			this.hseparator.Name = "hseparator";
			this.hbox1.Add (this.hseparator);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hseparator]));
			w2.Position = 1;
			this.vbox.Add (this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox [this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hscale = new global::Gtk.HScale (null);
			this.hscale.CanFocus = true;
			this.hscale.Name = "hscale";
			this.hscale.Adjustment.Upper = 100D;
			this.hscale.Adjustment.PageIncrement = 10D;
			this.hscale.Adjustment.StepIncrement = 1D;
			this.hscale.DrawValue = false;
			this.hscale.Digits = 0;
			this.hscale.ValuePos = ((global::Gtk.PositionType)(2));
			this.hbox2.Add (this.hscale);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hscale]));
			w4.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.spin = new global::Gtk.SpinButton (0D, 100D, 1D);
			this.spin.CanFocus = true;
			this.spin.Name = "spin";
			this.spin.Adjustment.PageIncrement = 10D;
			this.spin.ClimbRate = 1D;
			this.spin.Numeric = true;
			this.hbox2.Add (this.spin);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.spin]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button = new global::Gtk.Button ();
			this.button.CanFocus = true;
			this.button.Name = "button";
			this.button.UseUnderline = true;
			global::Gtk.Image w6 = new global::Gtk.Image ();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-back", global::Gtk.IconSize.Menu);
			this.button.Image = w6;
			this.hbox2.Add (this.button);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox.Add (this.hbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox [this.hbox2]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.Add (this.vbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
